compact: true
directory:
  - .
download-external-modules: false
evaluate-variables: true
framework:
  - terraform
output:
  - cli
quiet: true
skip-check:
  - CKV2_AZURE_31
skip-path:
  - tests/fixtures
soft-fail: false
